package shardctrler

//
// Shardctrler clerk.
//

import (
	"context"
	"crypto/rand"
	"math/big"
	"strings"

	"github.com/eraft-io/eraft/labrpc"
	"github.com/eraft-io/eraft/logger"
	"github.com/eraft-io/eraft/raftpb"
)

type Clerk struct {
	servers   []*labrpc.ClientEnd
	leaderId  int64
	clientId  int64 // generated by nrand(), it would be better to use some distributed ID generation algorithm that guarantees no conflicts
	commandId int64 // (clientId, commandId) defines a operation uniquely
}

func nrand() int64 {
	max := big.NewInt(int64(1) << 62)
	bigx, _ := rand.Int(rand.Reader, max)
	return bigx.Int64()
}

func MakeClerk(servers []*labrpc.ClientEnd) *Clerk {
	return &Clerk{
		servers:   servers,
		leaderId:  0,
		clientId:  nrand(),
		commandId: 0,
	}
}

func (ck *Clerk) Query(num int) Config {
	return ck.Command(&CommandRequest{Num: num, Op: OpQuery})
}

func (ck *Clerk) Join(servers map[int][]string) {
	ck.Command(&CommandRequest{Servers: servers, Op: OpJoin})
}

func (ck *Clerk) Leave(gids []int) {
	ck.Command(&CommandRequest{GIDs: gids, Op: OpLeave})
}

func (ck *Clerk) Move(shard int, gid int) {
	ck.Command(&CommandRequest{Shard: shard, GID: gid, Op: OpMove})
}

func pbConfigToConfig(pbConfig *raftpb.Config) Config {
	if pbConfig == nil {
		return Config{}
	}

	config := Config{
		Num:    int(pbConfig.Num),
		Shards: [10]int{}, // Initialize as fixed-size array
	}

	// Copy up to 10 elements from pbConfig.Buckets to config.Shards
	for i := 0; i < len(pbConfig.Buckets) && i < 10; i++ {
		config.Shards[i] = int(pbConfig.Buckets[i])
	}

	// copy server groups
	config.Groups = make(map[int][]string)
	for gid, servers := range pbConfig.Sgroups {
		config.Groups[int(gid)] = make([]string, len(strings.Split(servers, ",")))
		copy(config.Groups[int(gid)], strings.Split(servers, ","))
	}

	return config
}

// you can send an RPC with code like this:
// ok := ck.servers[i].Call("ShardCtrler.Command", &request, &response)
//
// the types of args and reply (including whether they are pointers)
// must match the declared types of the RPC handler function's
// arguments. and reply must be passed as a pointer.
func (ck *Clerk) Command(request *CommandRequest) Config {
	request.ClientId, request.CommandId = ck.clientId, ck.commandId
	for {
		var response CommandResponse
		if ck.servers[ck.leaderId].GrpcClient != nil {
			_req := &raftpb.ConfigCommandRequest{}
			// Convert map[int][]string to map[int64]string
			_req.Sgroups = make(map[int64]string)
			for gid, servers := range request.Servers {
				_req.Sgroups[int64(gid)] = strings.Join(servers, ",")
			}
			_req.Gids = make([]int64, len(request.GIDs)) // Use the correct field name based on your proto definition
			for i, gid := range request.GIDs {
				_req.Gids[i] = int64(gid)
			}
			_req.ShardId = int64(request.Shard)
			_req.Gid = int64(request.GID)
			_req.Num = int64(request.Num)
			_req.OpType = raftpb.ConfigOpType(request.Op)
			_req.ClientId = int64(request.ClientId)
			_req.CommandId = int64(request.CommandId)
			_resp, err := (*ck.servers[ck.leaderId].GrpcClient.SvrCli).ConfigCommandRPC(context.Background(), _req)
			if err != nil {
				logger.ELogger().Sugar().Warnf("[Client %d] Failed to call ConfigCommandRPC: %v", ck.clientId, err)
				ck.leaderId = (ck.leaderId + 1) % int64(len(ck.servers))
				continue
			}
			if _resp.ErrCode == int64(ErrWrongLeader) || _resp.ErrCode == int64(ErrTimeout) {
				ck.leaderId = (ck.leaderId + 1) % int64(len(ck.servers))
				continue
			}
			response.Err = Err(_resp.ErrCode)
			response.Config = pbConfigToConfig(_resp.Config) // Fixed line
		} else {
			if !ck.servers[ck.leaderId].Call("ShardCtrler.Command", request, &response) || response.Err == ErrWrongLeader || response.Err == ErrTimeout {
				ck.leaderId = (ck.leaderId + 1) % int64(len(ck.servers))
				continue
			}
		}
		ck.commandId++
		return response.Config
	}
}
