// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocessor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_coprocessor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_coprocessor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "errorpb.pb.h"
#include "kvrpcpb.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_coprocessor_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_coprocessor_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_coprocessor_2eproto;
namespace coprocessor {
class KeyRange;
class KeyRangeDefaultTypeInternal;
extern KeyRangeDefaultTypeInternal _KeyRange_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace coprocessor
PROTOBUF_NAMESPACE_OPEN
template<> ::coprocessor::KeyRange* Arena::CreateMaybeMessage<::coprocessor::KeyRange>(Arena*);
template<> ::coprocessor::Request* Arena::CreateMaybeMessage<::coprocessor::Request>(Arena*);
template<> ::coprocessor::Response* Arena::CreateMaybeMessage<::coprocessor::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace coprocessor {

// ===================================================================

class KeyRange :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coprocessor.KeyRange) */ {
 public:
  KeyRange();
  virtual ~KeyRange();

  KeyRange(const KeyRange& from);
  KeyRange(KeyRange&& from) noexcept
    : KeyRange() {
    *this = ::std::move(from);
  }

  inline KeyRange& operator=(const KeyRange& from) {
    CopyFrom(from);
    return *this;
  }
  inline KeyRange& operator=(KeyRange&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KeyRange& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KeyRange* internal_default_instance() {
    return reinterpret_cast<const KeyRange*>(
               &_KeyRange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(KeyRange* other);
  friend void swap(KeyRange& a, KeyRange& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KeyRange* New() const final {
    return CreateMaybeMessage<KeyRange>(nullptr);
  }

  KeyRange* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KeyRange>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KeyRange& from);
  void MergeFrom(const KeyRange& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KeyRange* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coprocessor.KeyRange";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_coprocessor_2eproto);
    return ::descriptor_table_coprocessor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes start = 1;
  void clear_start();
  static const int kStartFieldNumber = 1;
  const std::string& start() const;
  void set_start(const std::string& value);
  void set_start(std::string&& value);
  void set_start(const char* value);
  void set_start(const void* value, size_t size);
  std::string* mutable_start();
  std::string* release_start();
  void set_allocated_start(std::string* start);

  // bytes end = 2;
  void clear_end();
  static const int kEndFieldNumber = 2;
  const std::string& end() const;
  void set_end(const std::string& value);
  void set_end(std::string&& value);
  void set_end(const char* value);
  void set_end(const void* value, size_t size);
  std::string* mutable_end();
  std::string* release_end();
  void set_allocated_end(std::string* end);

  // @@protoc_insertion_point(class_scope:coprocessor.KeyRange)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr start_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr end_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_coprocessor_2eproto;
};
// -------------------------------------------------------------------

class Request :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coprocessor.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(nullptr);
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coprocessor.Request";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_coprocessor_2eproto);
    return ::descriptor_table_coprocessor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .coprocessor.KeyRange ranges = 4;
  int ranges_size() const;
  void clear_ranges();
  static const int kRangesFieldNumber = 4;
  ::coprocessor::KeyRange* mutable_ranges(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coprocessor::KeyRange >*
      mutable_ranges();
  const ::coprocessor::KeyRange& ranges(int index) const;
  ::coprocessor::KeyRange* add_ranges();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coprocessor::KeyRange >&
      ranges() const;

  // bytes data = 3;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);

  // .kvrpcpb.Context context = 1;
  bool has_context() const;
  void clear_context();
  static const int kContextFieldNumber = 1;
  const ::kvrpcpb::Context& context() const;
  ::kvrpcpb::Context* release_context();
  ::kvrpcpb::Context* mutable_context();
  void set_allocated_context(::kvrpcpb::Context* context);

  // int64 tp = 2;
  void clear_tp();
  static const int kTpFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int64 tp() const;
  void set_tp(::PROTOBUF_NAMESPACE_ID::int64 value);

  // uint64 start_ts = 7;
  void clear_start_ts();
  static const int kStartTsFieldNumber = 7;
  ::PROTOBUF_NAMESPACE_ID::uint64 start_ts() const;
  void set_start_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:coprocessor.Request)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coprocessor::KeyRange > ranges_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::kvrpcpb::Context* context_;
  ::PROTOBUF_NAMESPACE_ID::int64 tp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 start_ts_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_coprocessor_2eproto;
};
// -------------------------------------------------------------------

class Response :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coprocessor.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coprocessor.Response";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_coprocessor_2eproto);
    return ::descriptor_table_coprocessor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 1;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);

  // string other_error = 4;
  void clear_other_error();
  static const int kOtherErrorFieldNumber = 4;
  const std::string& other_error() const;
  void set_other_error(const std::string& value);
  void set_other_error(std::string&& value);
  void set_other_error(const char* value);
  void set_other_error(const char* value, size_t size);
  std::string* mutable_other_error();
  std::string* release_other_error();
  void set_allocated_other_error(std::string* other_error);

  // .errorpb.Error region_error = 2;
  bool has_region_error() const;
  void clear_region_error();
  static const int kRegionErrorFieldNumber = 2;
  const ::errorpb::Error& region_error() const;
  ::errorpb::Error* release_region_error();
  ::errorpb::Error* mutable_region_error();
  void set_allocated_region_error(::errorpb::Error* region_error);

  // .kvrpcpb.LockInfo locked = 3;
  bool has_locked() const;
  void clear_locked();
  static const int kLockedFieldNumber = 3;
  const ::kvrpcpb::LockInfo& locked() const;
  ::kvrpcpb::LockInfo* release_locked();
  ::kvrpcpb::LockInfo* mutable_locked();
  void set_allocated_locked(::kvrpcpb::LockInfo* locked);

  // .coprocessor.KeyRange range = 5;
  bool has_range() const;
  void clear_range();
  static const int kRangeFieldNumber = 5;
  const ::coprocessor::KeyRange& range() const;
  ::coprocessor::KeyRange* release_range();
  ::coprocessor::KeyRange* mutable_range();
  void set_allocated_range(::coprocessor::KeyRange* range);

  // @@protoc_insertion_point(class_scope:coprocessor.Response)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr other_error_;
  ::errorpb::Error* region_error_;
  ::kvrpcpb::LockInfo* locked_;
  ::coprocessor::KeyRange* range_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_coprocessor_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KeyRange

// bytes start = 1;
inline void KeyRange::clear_start() {
  start_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& KeyRange::start() const {
  // @@protoc_insertion_point(field_get:coprocessor.KeyRange.start)
  return start_.GetNoArena();
}
inline void KeyRange::set_start(const std::string& value) {
  
  start_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocessor.KeyRange.start)
}
inline void KeyRange::set_start(std::string&& value) {
  
  start_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocessor.KeyRange.start)
}
inline void KeyRange::set_start(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  start_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocessor.KeyRange.start)
}
inline void KeyRange::set_start(const void* value, size_t size) {
  
  start_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocessor.KeyRange.start)
}
inline std::string* KeyRange::mutable_start() {
  
  // @@protoc_insertion_point(field_mutable:coprocessor.KeyRange.start)
  return start_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* KeyRange::release_start() {
  // @@protoc_insertion_point(field_release:coprocessor.KeyRange.start)
  
  return start_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void KeyRange::set_allocated_start(std::string* start) {
  if (start != nullptr) {
    
  } else {
    
  }
  start_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), start);
  // @@protoc_insertion_point(field_set_allocated:coprocessor.KeyRange.start)
}

// bytes end = 2;
inline void KeyRange::clear_end() {
  end_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& KeyRange::end() const {
  // @@protoc_insertion_point(field_get:coprocessor.KeyRange.end)
  return end_.GetNoArena();
}
inline void KeyRange::set_end(const std::string& value) {
  
  end_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocessor.KeyRange.end)
}
inline void KeyRange::set_end(std::string&& value) {
  
  end_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocessor.KeyRange.end)
}
inline void KeyRange::set_end(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  end_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocessor.KeyRange.end)
}
inline void KeyRange::set_end(const void* value, size_t size) {
  
  end_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocessor.KeyRange.end)
}
inline std::string* KeyRange::mutable_end() {
  
  // @@protoc_insertion_point(field_mutable:coprocessor.KeyRange.end)
  return end_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* KeyRange::release_end() {
  // @@protoc_insertion_point(field_release:coprocessor.KeyRange.end)
  
  return end_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void KeyRange::set_allocated_end(std::string* end) {
  if (end != nullptr) {
    
  } else {
    
  }
  end_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), end);
  // @@protoc_insertion_point(field_set_allocated:coprocessor.KeyRange.end)
}

// -------------------------------------------------------------------

// Request

// .kvrpcpb.Context context = 1;
inline bool Request::has_context() const {
  return this != internal_default_instance() && context_ != nullptr;
}
inline const ::kvrpcpb::Context& Request::context() const {
  const ::kvrpcpb::Context* p = context_;
  // @@protoc_insertion_point(field_get:coprocessor.Request.context)
  return p != nullptr ? *p : *reinterpret_cast<const ::kvrpcpb::Context*>(
      &::kvrpcpb::_Context_default_instance_);
}
inline ::kvrpcpb::Context* Request::release_context() {
  // @@protoc_insertion_point(field_release:coprocessor.Request.context)
  
  ::kvrpcpb::Context* temp = context_;
  context_ = nullptr;
  return temp;
}
inline ::kvrpcpb::Context* Request::mutable_context() {
  
  if (context_ == nullptr) {
    auto* p = CreateMaybeMessage<::kvrpcpb::Context>(GetArenaNoVirtual());
    context_ = p;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Request.context)
  return context_;
}
inline void Request::set_allocated_context(::kvrpcpb::Context* context) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(context_);
  }
  if (context) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      context = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, context, submessage_arena);
    }
    
  } else {
    
  }
  context_ = context;
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Request.context)
}

// int64 tp = 2;
inline void Request::clear_tp() {
  tp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Request::tp() const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.tp)
  return tp_;
}
inline void Request::set_tp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tp_ = value;
  // @@protoc_insertion_point(field_set:coprocessor.Request.tp)
}

// bytes data = 3;
inline void Request::clear_data() {
  data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Request::data() const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.data)
  return data_.GetNoArena();
}
inline void Request::set_data(const std::string& value) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocessor.Request.data)
}
inline void Request::set_data(std::string&& value) {
  
  data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocessor.Request.data)
}
inline void Request::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocessor.Request.data)
}
inline void Request::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocessor.Request.data)
}
inline std::string* Request::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:coprocessor.Request.data)
  return data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Request::release_data() {
  // @@protoc_insertion_point(field_release:coprocessor.Request.data)
  
  return data_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Request.data)
}

// uint64 start_ts = 7;
inline void Request::clear_start_ts() {
  start_ts_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Request::start_ts() const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.start_ts)
  return start_ts_;
}
inline void Request::set_start_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  start_ts_ = value;
  // @@protoc_insertion_point(field_set:coprocessor.Request.start_ts)
}

// repeated .coprocessor.KeyRange ranges = 4;
inline int Request::ranges_size() const {
  return ranges_.size();
}
inline void Request::clear_ranges() {
  ranges_.Clear();
}
inline ::coprocessor::KeyRange* Request::mutable_ranges(int index) {
  // @@protoc_insertion_point(field_mutable:coprocessor.Request.ranges)
  return ranges_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coprocessor::KeyRange >*
Request::mutable_ranges() {
  // @@protoc_insertion_point(field_mutable_list:coprocessor.Request.ranges)
  return &ranges_;
}
inline const ::coprocessor::KeyRange& Request::ranges(int index) const {
  // @@protoc_insertion_point(field_get:coprocessor.Request.ranges)
  return ranges_.Get(index);
}
inline ::coprocessor::KeyRange* Request::add_ranges() {
  // @@protoc_insertion_point(field_add:coprocessor.Request.ranges)
  return ranges_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coprocessor::KeyRange >&
Request::ranges() const {
  // @@protoc_insertion_point(field_list:coprocessor.Request.ranges)
  return ranges_;
}

// -------------------------------------------------------------------

// Response

// bytes data = 1;
inline void Response::clear_data() {
  data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::data() const {
  // @@protoc_insertion_point(field_get:coprocessor.Response.data)
  return data_.GetNoArena();
}
inline void Response::set_data(const std::string& value) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocessor.Response.data)
}
inline void Response::set_data(std::string&& value) {
  
  data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocessor.Response.data)
}
inline void Response::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocessor.Response.data)
}
inline void Response::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocessor.Response.data)
}
inline std::string* Response::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.data)
  return data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_data() {
  // @@protoc_insertion_point(field_release:coprocessor.Response.data)
  
  return data_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.data)
}

// .errorpb.Error region_error = 2;
inline bool Response::has_region_error() const {
  return this != internal_default_instance() && region_error_ != nullptr;
}
inline const ::errorpb::Error& Response::region_error() const {
  const ::errorpb::Error* p = region_error_;
  // @@protoc_insertion_point(field_get:coprocessor.Response.region_error)
  return p != nullptr ? *p : *reinterpret_cast<const ::errorpb::Error*>(
      &::errorpb::_Error_default_instance_);
}
inline ::errorpb::Error* Response::release_region_error() {
  // @@protoc_insertion_point(field_release:coprocessor.Response.region_error)
  
  ::errorpb::Error* temp = region_error_;
  region_error_ = nullptr;
  return temp;
}
inline ::errorpb::Error* Response::mutable_region_error() {
  
  if (region_error_ == nullptr) {
    auto* p = CreateMaybeMessage<::errorpb::Error>(GetArenaNoVirtual());
    region_error_ = p;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.region_error)
  return region_error_;
}
inline void Response::set_allocated_region_error(::errorpb::Error* region_error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(region_error_);
  }
  if (region_error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      region_error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, region_error, submessage_arena);
    }
    
  } else {
    
  }
  region_error_ = region_error;
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.region_error)
}

// .kvrpcpb.LockInfo locked = 3;
inline bool Response::has_locked() const {
  return this != internal_default_instance() && locked_ != nullptr;
}
inline const ::kvrpcpb::LockInfo& Response::locked() const {
  const ::kvrpcpb::LockInfo* p = locked_;
  // @@protoc_insertion_point(field_get:coprocessor.Response.locked)
  return p != nullptr ? *p : *reinterpret_cast<const ::kvrpcpb::LockInfo*>(
      &::kvrpcpb::_LockInfo_default_instance_);
}
inline ::kvrpcpb::LockInfo* Response::release_locked() {
  // @@protoc_insertion_point(field_release:coprocessor.Response.locked)
  
  ::kvrpcpb::LockInfo* temp = locked_;
  locked_ = nullptr;
  return temp;
}
inline ::kvrpcpb::LockInfo* Response::mutable_locked() {
  
  if (locked_ == nullptr) {
    auto* p = CreateMaybeMessage<::kvrpcpb::LockInfo>(GetArenaNoVirtual());
    locked_ = p;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.locked)
  return locked_;
}
inline void Response::set_allocated_locked(::kvrpcpb::LockInfo* locked) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(locked_);
  }
  if (locked) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      locked = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, locked, submessage_arena);
    }
    
  } else {
    
  }
  locked_ = locked;
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.locked)
}

// string other_error = 4;
inline void Response::clear_other_error() {
  other_error_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Response::other_error() const {
  // @@protoc_insertion_point(field_get:coprocessor.Response.other_error)
  return other_error_.GetNoArena();
}
inline void Response::set_other_error(const std::string& value) {
  
  other_error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocessor.Response.other_error)
}
inline void Response::set_other_error(std::string&& value) {
  
  other_error_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:coprocessor.Response.other_error)
}
inline void Response::set_other_error(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  other_error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocessor.Response.other_error)
}
inline void Response::set_other_error(const char* value, size_t size) {
  
  other_error_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocessor.Response.other_error)
}
inline std::string* Response::mutable_other_error() {
  
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.other_error)
  return other_error_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Response::release_other_error() {
  // @@protoc_insertion_point(field_release:coprocessor.Response.other_error)
  
  return other_error_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_other_error(std::string* other_error) {
  if (other_error != nullptr) {
    
  } else {
    
  }
  other_error_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), other_error);
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.other_error)
}

// .coprocessor.KeyRange range = 5;
inline bool Response::has_range() const {
  return this != internal_default_instance() && range_ != nullptr;
}
inline void Response::clear_range() {
  if (GetArenaNoVirtual() == nullptr && range_ != nullptr) {
    delete range_;
  }
  range_ = nullptr;
}
inline const ::coprocessor::KeyRange& Response::range() const {
  const ::coprocessor::KeyRange* p = range_;
  // @@protoc_insertion_point(field_get:coprocessor.Response.range)
  return p != nullptr ? *p : *reinterpret_cast<const ::coprocessor::KeyRange*>(
      &::coprocessor::_KeyRange_default_instance_);
}
inline ::coprocessor::KeyRange* Response::release_range() {
  // @@protoc_insertion_point(field_release:coprocessor.Response.range)
  
  ::coprocessor::KeyRange* temp = range_;
  range_ = nullptr;
  return temp;
}
inline ::coprocessor::KeyRange* Response::mutable_range() {
  
  if (range_ == nullptr) {
    auto* p = CreateMaybeMessage<::coprocessor::KeyRange>(GetArenaNoVirtual());
    range_ = p;
  }
  // @@protoc_insertion_point(field_mutable:coprocessor.Response.range)
  return range_;
}
inline void Response::set_allocated_range(::coprocessor::KeyRange* range) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete range_;
  }
  if (range) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      range = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, range, submessage_arena);
    }
    
  } else {
    
  }
  range_ = range;
  // @@protoc_insertion_point(field_set_allocated:coprocessor.Response.range)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace coprocessor

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_coprocessor_2eproto
