[package]
name = "pmem_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corundum = { git = "https://github.com/NVSL/Corundum.git" }
