// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kvraftpb/kvraft.proto

package kvraftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_PUT    Op = 0
	Op_APPEND Op = 1
	Op_GET    Op = 2
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "PUT",
		1: "APPEND",
		2: "GET",
	}
	Op_value = map[string]int32{
		"PUT":    0,
		"APPEND": 1,
		"GET":    2,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_kvraftpb_kvraft_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_kvraftpb_kvraft_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_kvraftpb_kvraft_proto_rawDescGZIP(), []int{0}
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            Op                     `protobuf:"varint,3,opt,name=op,proto3,enum=kvraftpb.Op" json:"op,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CommandId     int64                  `protobuf:"varint,5,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_kvraftpb_kvraft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvraftpb_kvraft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_kvraftpb_kvraft_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommandRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CommandRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_PUT
}

func (x *CommandRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CommandRequest) GetCommandId() int64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_kvraftpb_kvraft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvraftpb_kvraft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_kvraftpb_kvraft_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *CommandResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_kvraftpb_kvraft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvraftpb_kvraft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_kvraftpb_kvraft_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Term          int64                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LastApplied   int64                  `protobuf:"varint,4,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	CommitIndex   int64                  `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_kvraftpb_kvraft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvraftpb_kvraft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_kvraftpb_kvraft_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatusResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GetStatusResponse) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *GetStatusResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

var File_kvraftpb_kvraft_proto protoreflect.FileDescriptor

const file_kvraftpb_kvraft_proto_rawDesc = "" +
	"\n" +
	"\x15kvraftpb/kvraft.proto\x12\bkvraftpb\"\x92\x01\n" +
	"\x0eCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1c\n" +
	"\x02op\x18\x03 \x01(\x0e2\f.kvraftpb.OpR\x02op\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x05 \x01(\x03R\tcommandId\"9\n" +
	"\x0fCommandResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x12\n" +
	"\x10GetStatusRequest\"\x93\x01\n" +
	"\x11GetStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x03R\x04term\x12!\n" +
	"\flast_applied\x18\x04 \x01(\x03R\vlastApplied\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x03R\vcommitIndex*\"\n" +
	"\x02Op\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06APPEND\x10\x01\x12\a\n" +
	"\x03GET\x10\x022\x91\x01\n" +
	"\tKVService\x12>\n" +
	"\aCommand\x12\x18.kvraftpb.CommandRequest\x1a\x19.kvraftpb.CommandResponse\x12D\n" +
	"\tGetStatus\x12\x1a.kvraftpb.GetStatusRequest\x1a\x1b.kvraftpb.GetStatusResponseB$Z\"github.com/eraft-io/eraft/kvraftpbb\x06proto3"

var (
	file_kvraftpb_kvraft_proto_rawDescOnce sync.Once
	file_kvraftpb_kvraft_proto_rawDescData []byte
)

func file_kvraftpb_kvraft_proto_rawDescGZIP() []byte {
	file_kvraftpb_kvraft_proto_rawDescOnce.Do(func() {
		file_kvraftpb_kvraft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvraftpb_kvraft_proto_rawDesc), len(file_kvraftpb_kvraft_proto_rawDesc)))
	})
	return file_kvraftpb_kvraft_proto_rawDescData
}

var file_kvraftpb_kvraft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvraftpb_kvraft_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kvraftpb_kvraft_proto_goTypes = []any{
	(Op)(0),                   // 0: kvraftpb.Op
	(*CommandRequest)(nil),    // 1: kvraftpb.CommandRequest
	(*CommandResponse)(nil),   // 2: kvraftpb.CommandResponse
	(*GetStatusRequest)(nil),  // 3: kvraftpb.GetStatusRequest
	(*GetStatusResponse)(nil), // 4: kvraftpb.GetStatusResponse
}
var file_kvraftpb_kvraft_proto_depIdxs = []int32{
	0, // 0: kvraftpb.CommandRequest.op:type_name -> kvraftpb.Op
	1, // 1: kvraftpb.KVService.Command:input_type -> kvraftpb.CommandRequest
	3, // 2: kvraftpb.KVService.GetStatus:input_type -> kvraftpb.GetStatusRequest
	2, // 3: kvraftpb.KVService.Command:output_type -> kvraftpb.CommandResponse
	4, // 4: kvraftpb.KVService.GetStatus:output_type -> kvraftpb.GetStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kvraftpb_kvraft_proto_init() }
func file_kvraftpb_kvraft_proto_init() {
	if File_kvraftpb_kvraft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvraftpb_kvraft_proto_rawDesc), len(file_kvraftpb_kvraft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvraftpb_kvraft_proto_goTypes,
		DependencyIndexes: file_kvraftpb_kvraft_proto_depIdxs,
		EnumInfos:         file_kvraftpb_kvraft_proto_enumTypes,
		MessageInfos:      file_kvraftpb_kvraft_proto_msgTypes,
	}.Build()
	File_kvraftpb_kvraft_proto = out.File
	file_kvraftpb_kvraft_proto_goTypes = nil
	file_kvraftpb_kvraft_proto_depIdxs = nil
}
